version: '3'

services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        env_file: .env
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - comment-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - comment-network

    #MySQL Service
    db:
        image: mysql:8
        platform: linux/x86_64
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: comment_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - commentData:/var/lib/mysql
        networks:
            - comment-network

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always
        networks:
            - comment-network

#Docker Networks
networks:
    comment-network:
        driver: bridge

#Volumes
volumes:
    commentData:
        driver: local
